### ISSUE TITLE
Cannot create a database with the same name as a deleted one

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/Arachne#10]
1. Login to Arachne Data Node
2. Go to Administration → Databases
3. Create a database with valid parameters (e.g. copy an existing one) and a unique name
4. Delete the database
5. Create another database with the same name as on the step # 3

Expected result: creating is possible since the previous database has been deleted
Actual result: a new database is not created because it has the same name as the database from the step # 3 which has already been deleted

**Comment by ttemnikova** [comment]
I still observe this issue on our Ody stand

**Comment by konstjar** [comment]
As discussed:
- Connection check should not be a part of adding datasource action
- We want to have a separate button on UI to check connection
- Connection check should be done though Execution Engine

**Comment by ttemnikova** [comment]
I was able to create a data source with the same name as a deleted one
