### ISSUE TITLE
Whitelabel Error after reloading page

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/Arachne#13]
1. Login to  Arachne Data Node
2. Go to the list of submissions or to the Administration panel
3. Reload the page

Expected result: the page is reloaded, the user is logged in and see the page opened on the step # 2
Actual result: Whitelabel Error Page, the user has to go to the main page and repeat the navigation inside the application
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
There was an unexpected error (type=Not Found, status=404).
```

**Comment by konstjar** [comment]
It's related to configuration of Nginx that works as proxy pass for the application.

**Comment by konstjar** [comment]
Agreed to fix on the application side.
