### ISSUE TITLE
No redirect to the list after deleting a database

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/Arachne#14]
Prerequisites: there is at least one database created

1. Login to Arachne Data Node
2. Go to Administration → Databases
3. Open a database from the list
4. Click the "Delete" button
5. Confirm the deletion

Expected result: the user is redirected to the list of databases, the database which has been deleted in the test does not exist in the lsit
Actual result: the user remains on the Database View screen

**Comment by odbz** [comment]
Bug fixed
