### ISSUE TITLE
List of Databases: DBMS Type is not shown (floating bug)

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/Arachne#15]
Sometimes when I do:

1. Login to Arachne Data Node
2. Go to Administration → Databases

I get '-'s instead of database types in the list of databases. When I sort the list of databases or navigate to another page of Arachne Data Node and go back to the list of databases, the types are shown correctly.
![image](https://github.com/OHDSI/Arachne/assets/95474802/c89c9b26-d2f1-4d2f-a535-615512793a0b)

**Comment by odbz** [comment]
I tested, and everything work fine
