### ISSUE TITLE
admin password in datanode.env file is not correctly passed to postgres

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#24]
The admin password in the datanode.env file is not correctly added the postgres database used by the app. (users table)

It seems to be truncated. 

Also would it be better to have the user configure an unencrypted password rather and an encrypted one? If the user is supposed to supply their password after it has been encrypted /hashed then they also need to know the hashing algorithm being used by the app and how to apply this algorithm to their password. Seems easier to just ask them for their password than to ask them for their already encrypted password right?

**Comment by konstjar** [comment]
Duplicate #28

**Comment by gorodonoff** [comment]
Fixed by pull request https://github.com/OHDSI/Arachne/pull/39
"password" --> 'password'
