### ISSUE TITLE
remove analysis type dropdown in the user interface

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#26]
<img width="521" alt="image" src="https://github.com/OHDSI/Arachne/assets/10227522/84d52649-ee9f-4e90-a24c-cb6adc6fd7cf">

In the Create Submission section of the app, Files in Archive will always be a custom analysis and Strategus JSON input will always be a "strategus" analysis type. So we don't need to ask the user to input the analysis type because there is only one option based on the type of input, (json or zip).

@anthonysena

**Comment by odbz** [comment]
bug fixed
