### ISSUE TITLE
Why do we have 2 different docker-compose files and environment settings?

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Arachne#29]
I was wondering why there are 2 different docker compose files in the repo?

1. https://github.com/OHDSI/Arachne/blob/master/install/docker/docker-compose.yml
2. https://github.com/OHDSI/Arachne/blob/master/install/docker/docker-compose-windows.yml

And that they reference different environment settings?

1. https://github.com/OHDSI/Arachne/blob/master/install/docker/docker-compose.yml#L61
2. https://github.com/OHDSI/Arachne/blob/master/install/docker/docker-compose-windows.yml#L58

Shouldn't these reference https://github.com/OHDSI/Arachne/blob/master/install/docker/datanode-example.env? I had to change this locally to spin up my containers and was curious about this.

**Comment by konstjar** [comment]
Great question!


https://github.com/OHDSI/Arachne/blob/master/install/docker/docker-compose-windows.yml
- This version is used in combination with powershell script and it was designed for Windows.
- This version uses tarball execution mode. And this is a reason for the different set of configuration options for Arachne Execution Engine.


https://github.com/OHDSI/Arachne/blob/master/install/docker/docker-compose.yml
- Could be used as general version of Docker compose
- Configured for Docker execution mode 

The comment about [datanode-example.env](https://github.com/OHDSI/Arachne/blob/master/install/docker/datanode-example.env) is reasonable. Let's rename it to avoid confusion.

**Comment by konstjar** [comment]
`datanode-example.env` was renamed to `datanode.env`

**Comment by konstjar** [comment]
With v2.0.3 we simplified deployment and only once docker compose file left.
