### ISSUE TITLE
issue using custom docker image for runtime

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#61]
I'm trying to try out a custom execution environment with Arachne. The image exists and I think it is publicly available. But when I try to use it in Arachne I get the following error.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/0ca7dc92-62fc-42c2-abe5-1ecc233e5346">

**Comment by ablack3** [comment]
@konstjar

**Comment by konstjar** [comment]
We will introduce new setting that similar to approach in Kubernetes:
https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy

**Comment by konstjar** [comment]
Addressed in the ARACHNE Execution Engine v2.5.0 introducing the new configuration option 

`docker.image.pull` - policy that defines when docker images should be pulled. The possible values are as follows:
`NEVER` - Never pull any images. If image does not exist in local repository, fail analysis.
`MISSING` - Default value. If image exists in local repository, use it. Do not check for updated image.
`ALWAYS` - Always attempt to pull. If pull failed but image exists in local repository, proceed with that image.
`FORCE` - Always attempt to pull. If pull fails, analysis will fail as well, even if local image exists.
