### ISSUE TITLE
rerun analysis does not allow me to select entry point

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#62]
If I select rerun and try to choose the entry point there is no option for an entry point.

<img width="720" alt="image" src="https://github.com/user-attachments/assets/0a012eb6-2f41-4360-9aaf-fb12a3b0a42f">

**Comment by ablack3** [comment]
Also when the app is in Docker mode and I rerun an analysis I am not able to enter the url to the docker image. Instead I have to select the environment from a dropdown similar to tarball mode.

**Comment by konstjar** [comment]
The second part of the issue was resolved in #71.

**Comment by dmitrys-odysseus** [comment]
The endpoint `GET /api/v1/analysis/{id}` response is updated to provide `files` field, that contains a list of analysis file names

**Comment by konstjar** [comment]
@SergeySukhanov can you please update UI?

**Comment by ttemnikova** [comment]
I was able to select an entry point
![image](https://github.com/user-attachments/assets/252f9bc2-6540-48d9-a9bd-694fbc2024c1)

The docker image filed is editable, and the typed value is taken in account in the request
![image](https://github.com/user-attachments/assets/9e7b0abc-e9d5-4990-8ea6-24d3e266924b)
