### ISSUE TITLE
disable environment descriptors when in Docker mode

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#66]
I'm not completely sure how descriptors are tied to the environments but for now can we simply disable calls to get descriptor files when in Docker mode to avoid errors like this one?

![image](https://github.com/user-attachments/assets/ff8880ec-ba1d-4834-af30-3126c5893b68)

The descriptor does not match the docker environment so it is not very helpful. However we could come up with a standard for providing descriptors along with the docker images in a future iteration.

**Comment by konstjar** [comment]
Closing as completed
