### ISSUE TITLE
Fatal error: cannot open file '/etc/analysis/main.R': No such file or directory

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#96]
I'm testing the new version of Arachne 2.0.3. I'm creating the simplest possible of the basic functionality that runs an R script in a Docker image.

Steps to reproduce the error.

Create a folder called TrivialTest and in that folder create an R script called hello.R

<img width="233" alt="image" src="https://github.com/user-attachments/assets/faee335d-7d09-437b-b8e1-7765c82efa7b">

In the hello.R file add one line `print("hello")`
<img width="533" alt="image" src="https://github.com/user-attachments/assets/6f11386f-0bc2-4518-b375-1ddaae572741">

Zip the TrivialTest folder and upload it to Arachne. 

<img width="701" alt="image" src="https://github.com/user-attachments/assets/23e82aff-47cd-4759-bd7a-6b99b73f360d">

As the entrypoint select the  hello.R file.

See the error
<img width="737" alt="image" src="https://github.com/user-attachments/assets/70127536-013d-491f-add5-54cd4e0bf2fd">

**Comment by konstjar** [comment]
Fixed in https://github.com/OHDSI/Arachne/pull/99
